version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
      - ${NGINX_SSL_EXTERNAL_PORT}:443
    volumes:
      - ./:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ${NETWORK_NAME}
    depends_on:
        - php
        - database

  database:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: ./.docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - ${NETWORK_NAME}

  php:
    build:
      context: ./
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: ${API_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - api_logs:/var/www/storage/logs/
    depends_on:
      - database
    networks:
      - ${NETWORK_NAME}
    entrypoint: /opt/docker-entrypoint.sh

  phpmyadmin:
      image: phpmyadmin
      container_name: ${PHPMYADMIN_CONTAINER_NAME}
      restart: unless-stopped
      ports:
          - ${PHPMYADMIN_EXTERNAL_PORT}:80
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=database
      networks:
          - ${NETWORK_NAME}

  mailcatcher:
      image: schickling/mailcatcher:latest
      container_name: ${MAILCATCHER_CONTAINER_NAME}
      restart: unless-stopped
      ports:
          - ${MAILCATCHER_EXTERNAL_SMTP_PORT}:1025
          - ${MAILCATCHER_EXTERNAL_HTTP_PORT}:1080
      networks:
          - ${NETWORK_NAME}

networks:
  PostsTestTask:
    driver: bridge

volumes:
  database:
    driver: local
  api_logs:

