#!/bin/bash

set -e
mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL

CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE DATABASE IF NOT EXISTS test;

USE $MYSQL_DATABASE;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO $MYSQL_USER;

USE test;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON test.* TO $MYSQL_USER;

EOSQL
